### ISSUE TITLE
Sei proprio un WEB DEVELOPER

### ISSUE THREAD

**Issue by andreafioraldi** [LeoBrizi/chiLhaVisto_project#1]
WWWWWEEEEEEEEEEBBBBBBBB DDDDDDDDEEEEEEEEEEEVVVVVVVVVVEEEEEEEELLLLLLLLLLOOOOOOOOOOOPPPPPPPPPEEEEEEEEEEEEERRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR

**Comment by LeoBrizi** [comment]
ecco perchè ho fatto crescere la barba ;)
